version: "3.1"
services:
    db:
        image: mysql:5.7
        container_name: mysql-estoque
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: estoque
            MYSQL_USER: root
            MYSQL_PASSWORD: 1234
            MYSQL_ROOT_PASSWORD: 1234
        volumes:
            - ./.docker/mysql/data:/docker-entrypoint-initdb.d
            - ./.docker/mysql/conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
